import flet, contextlib

# 💡 Flet 445개 전체 속성/위젯 한글 요약 사전
flet_korean_dict = {
    "AdaptiveControl": "적응형 컨트롤 (플랫폼에 따라 UI가 자동 변환되는 위젯의 기본 클래스)",
    "AlertDialog": "알림 대화상자 (팝업창)",
    "Alignment": "정렬 속성 (x, y 좌표를 통한 정렬)",
    "AnimatedSwitcher": "애니메이션 스위처 (자식 위젯이 바뀔 때 애니메이션 효과 적용)",
    "AnimatedSwitcherTransition": "애니메이션 스위처 전환 효과 설정",
    "Animation": "애니메이션 기본 설정",
    "AnimationCurve": "애니메이션 곡선 (속도 변화 곡선, 예: ease-in, bounce 등)",
    "AnimationStyle": "애니메이션 스타일 정의",
    "AppBar": "앱바 (화면 상단의 네비게이션/타이틀 바)",
    "AppBarTheme": "앱바 테마 설정",
    "AppLifecycleState": "앱 생명주기 상태 (활성화, 백그라운드 등)",
    "AppLifecycleStateChangeEvent": "앱 생명주기 상태 변경 이벤트",
    "AppView": "앱 뷰 모드 설정",
    "Assertiveness": "접근성(스크린 리더) 알림 강도 설정",
    "Audio": "오디오 플레이어 위젯",
    "AudioDurationChangeEvent": "오디오 길이(재생 시간) 변경 이벤트",
    "AudioEncoder": "오디오 인코더 포맷 설정",
    "AudioPositionChangeEvent": "오디오 재생 위치 변경 이벤트",
    "AudioRecorder": "오디오 녹음 위젯",
    "AudioRecorderState": "오디오 녹음기 상태 (녹음중, 정지 등)",
    "AudioRecorderStateChangeEvent": "오디오 녹음 상태 변경 이벤트",
    "AudioState": "오디오 재생 상태 (재생, 일시정지 등)",
    "AudioStateChangeEvent": "오디오 재생 상태 변경 이벤트",
    "AutoComplete": "자동완성 입력 필드",
    "AutoCompleteSelectEvent": "자동완성 항목 선택 이벤트",
    "AutoCompleteSuggestion": "자동완성 추천 항목",
    "AutofillGroup": "자동완성(비밀번호, 주소 등) 양식 그룹",
    "AutofillGroupDisposeAction": "자동완성 그룹 폐기 시 동작",
    "AutofillHint": "자동완성 힌트 타입 (이메일, 이름 등)",
    "Axis": "축 방향 (가로/세로)",
    "Badge": "배지 (아이콘 모서리에 숫자나 점을 표시하는 알림)",
    "BadgeTheme": "배지 테마 설정",
    "Banner": "배너 (상단에 고정되는 알림 위젯)",
    "BannerTheme": "배너 테마 설정",
    "BarChart": "막대그래프",
    "BarChartEvent": "막대그래프 상호작용 이벤트",
    "BarChartGroup": "막대그래프 데이터 그룹",
    "BarChartRod": "막대그래프의 개별 막대",
    "BarChartRodStackItem": "누적 막대그래프의 스택 아이템",
    "BeveledRectangleBorder": "모서리가 깎인 사각형 테두리",
    "BlendMode": "색상 혼합(블렌드) 모드",
    "Blur": "블러(흐림) 효과 설정",
    "BlurTileMode": "블러 타일(반복) 모드",
    "Border": "테두리 설정",
    "BorderRadius": "테두리 둥글기 설정",
    "BorderRadiusValue": "테두리 둥글기 수치",
    "BorderSide": "테두리 단면(한쪽 선) 설정",
    "BorderSideStrokeAlign": "테두리 선 정렬 방식 (안쪽, 바깥쪽, 중앙)",
    "BottomAppBar": "하단 앱바",
    "BottomAppBarTheme": "하단 앱바 테마 설정",
    "BottomSheet": "바텀 시트 (하단에서 위로 올라오는 패널)",
    "BottomSheetTheme": "바텀 시트 테마 설정",
    "BoxConstraints": "박스 크기 제약 조건 (최소/최대 너비 및 높이)",
    "BoxDecoration": "박스 꾸미기 (배경, 테두리, 그림자 등)",
    "BoxShadow": "박스 그림자 효과",
    "BoxShape": "박스 모양 (사각형, 원형 등)",
    "Brightness": "화면 밝기 모드 (라이트/다크)",
    "BrowserContextMenu": "브라우저 우클릭 컨텍스트 메뉴 제어",
    "Button": "기본 버튼 클래스",
    "ButtonStyle": "버튼 스타일 정의",
    "ButtonTheme": "버튼 전역 테마 설정",
    "Card": "카드 위젯 (그림자가 있는 패널)",
    "CardTheme": "카드 테마 설정",
    "CardVariant": "카드 디자인 변형 스타일",
    "ChartAxis": "차트 축 설정",
    "ChartAxisLabel": "차트 축 라벨 텍스트",
    "ChartCirclePoint": "차트 원형 데이터 포인트",
    "ChartCrossPoint": "차트 십자가형 데이터 포인트",
    "ChartGridLines": "차트 배경 그리드 선",
    "ChartPointLine": "차트 데이터 포인트를 잇는 선",
    "ChartPointShape": "차트 데이터 포인트 모양 기본 클래스",
    "ChartSquarePoint": "차트 사각형 데이터 포인트",
    "Checkbox": "체크박스 위젯",
    "CheckboxTheme": "체크박스 테마 설정",
    "Chip": "칩 (작은 둥근 태그/버튼 위젯)",
    "ChipTheme": "칩 테마 설정",
    "CircleAvatar": "원형 아바타 (프로필 이미지 등에 사용)",
    "CircleBorder": "원형 테두리",
    "ClipBehavior": "자식 위젯이 영역을 벗어날 때 자르기(Clip) 동작 설정",
    "ColorEnums": "색상 관련 열거형 데이터",
    "ColorFilter": "색상 필터 (이미지 등에 색상 필터 적용)",
    "ColorScheme": "색상 스키마 (Material Design 기반 전체 앱 색상 테마)",
    "ColorValue": "단일 색상 값",
    "Colors": "Flet 내장 기본 색상 모음",
    "Column": "세로 정렬 레이아웃",
    "Container": "컨테이너 (여백, 테두리, 배경을 가지는 다목적 박스)",
    "ContainerTapEvent": "컨테이너 탭/클릭 이벤트",
    "ContinuousRectangleBorder": "부드러운 곡선의 사각형 테두리 (애플 스타일)",
    "Control": "모든 Flet 위젯의 최상위 부모 클래스",
    "ControlEvent": "컨트롤(위젯) 이벤트 기본 클래스",
    "ControlEventType": "이벤트 타입",
    "ControlState": "위젯의 상태 (호버, 포커스, 비활성화 등)",
    "ControlStateValue": "상태별 값 설정",
    "CrossAxisAlignment": "교차축(반대축) 정렬 방식",
    "CupertinoActionSheet": "iOS 스타일 액션 시트 (하단 팝업 메뉴)",
    "CupertinoActionSheetAction": "iOS 액션 시트의 개별 버튼",
    "CupertinoActivityIndicator": "iOS 스타일 로딩 스피너",
    "CupertinoAlertDialog": "iOS 스타일 알림 대화상자",
    "CupertinoAppBar": "iOS 스타일 상단 네비게이션 바",
    "CupertinoBottomSheet": "iOS 스타일 바텀 시트",
    "CupertinoButton": "iOS 스타일 버튼",
    "CupertinoCheckbox": "iOS 스타일 체크박스",
    "CupertinoColors": "iOS (Cupertino) 전용 색상 모음",
    "CupertinoContextMenu": "iOS 스타일 컨텍스트 메뉴 (길게 누르기 메뉴)",
    "CupertinoContextMenuAction": "iOS 컨텍스트 메뉴의 개별 액션",
    "CupertinoDatePicker": "iOS 스타일 날짜 선택기 (드럼롤 방식)",
    "CupertinoDatePickerDateOrder": "iOS 날짜 선택기의 연/월/일 표시 순서",
    "CupertinoDatePickerMode": "iOS 날짜 선택기 모드 (날짜, 시간 등)",
    "CupertinoDialogAction": "iOS 대화상자 버튼 액션",
    "CupertinoFilledButton": "iOS 스타일 색상이 채워진 버튼",
    "CupertinoIcons": "iOS 전용 아이콘 모음",
    "CupertinoListTile": "iOS 스타일 리스트 항목 (설정창 스타일)",
    "CupertinoNavigationBar": "iOS 스타일 하단 탭바",
    "CupertinoPicker": "iOS 스타일 일반 항목 선택기 (드럼롤)",
    "CupertinoRadio": "iOS 스타일 라디오 버튼",
    "CupertinoSegmentedButton": "iOS 스타일 분할 탭 버튼",
    "CupertinoSlider": "iOS 스타일 슬라이더",
    "CupertinoSlidingSegmentedButton": "iOS 스타일 슬라이딩 분할 탭 버튼 (배경이 움직이는 탭)",
    "CupertinoSwitch": "iOS 스타일 토글 스위치",
    "CupertinoTextField": "iOS 스타일 텍스트 입력 필드",
    "CupertinoTimerPicker": "iOS 스타일 타이머 선택기",
    "CupertinoTimerPickerMode": "iOS 타이머 선택기 모드",
    "DataCell": "데이터 테이블의 개별 셀",
    "DataColumn": "데이터 테이블의 열 제목",
    "DataColumnSortEvent": "데이터 테이블 열 정렬 이벤트",
    "DataRow": "데이터 테이블의 한 행",
    "DataTable": "데이터 테이블 (표 형태 레이아웃)",
    "DataTableTheme": "데이터 테이블 테마 설정",
    "DatePicker": "안드로이드(Material) 스타일 날짜 선택기",
    "DatePickerEntryMode": "날짜 선택기 입력 모드 (달력 선택 vs 직접 타이핑)",
    "DatePickerEntryModeChangeEvent": "날짜 선택기 입력 모드 변경 이벤트",
    "DatePickerMode": "날짜 선택기 보기 모드 (연도별 vs 월별)",
    "DatePickerTheme": "날짜 선택기 테마 설정",
    "DateTimeValue": "날짜/시간 데이터 값",
    "DecorationImage": "컨테이너 배경 등에 쓰이는 꾸미기용 이미지",
    "DialogTheme": "대화상자(팝업) 테마 설정",
    "DismissDirection": "밀어서 지우기(스와이프) 허용 방향",
    "Dismissible": "밀어서 지우기가 가능한 래퍼 위젯",
    "DismissibleDismissEvent": "밀어서 지우기 완료 이벤트",
    "DismissibleUpdateEvent": "밀어서 지우기 진행중(업데이트) 이벤트",
    "Divider": "가로 구분선",
    "DividerTheme": "구분선 테마 설정",
    "DragEndEvent": "드래그 종료 이벤트",
    "DragStartEvent": "드래그 시작 이벤트",
    "DragTarget": "드래그 앤 드롭에서 항목을 놓을 수 있는 도착 지점 위젯",
    "DragTargetEvent": "드래그 타겟 상호작용 이벤트",
    "DragUpdateEvent": "드래그 진행중 이벤트",
    "Draggable": "드래그 앤 드롭이 가능한 위젯",
    "Dropdown": "드롭다운 (선택 메뉴)",
    "DropdownM2": "드롭다운 (Material 2 이전 스타일 버전)",
    "DropdownOption": "드롭다운 안의 개별 선택 항목",
    "Duration": "시간(기간) 설정 객체",
    "DurationValue": "시간(기간) 값",
    "ElevatedButton": "입체감이 있는 일반 버튼",
    "ElevatedButtonTheme": "입체 버튼 테마 설정",
    "EventType": "일반 이벤트 타입 열거형",
    "ExpansionPanel": "확장 패널 (클릭 시 아래로 내용이 열리는 패널)",
    "ExpansionPanelList": "확장 패널들의 리스트 모음",
    "ExpansionTile": "확장 타일 (리스트 항목이 열리면서 세부내용 표시)",
    "ExpansionTileTheme": "확장 타일 테마 설정",
    "FLET_APP": "Flet 앱 실행 상수",
    "FLET_APP_HIDDEN": "Flet 숨김 모드 앱 실행 상수",
    "FLET_APP_WEB": "Flet 웹 브라우저 앱 실행 상수",
    "FilePicker": "파일 탐색기 (파일 열기/저장 다이얼로그 호출)",
    "FilePickerFileType": "파일 탐색기 허용 파일 확장자 타입",
    "FilePickerResultEvent": "파일 선택 완료 결과 이벤트",
    "FilePickerUploadEvent": "파일 업로드 진행 이벤트",
    "FilePickerUploadFile": "업로드 대상 파일 객체",
    "FilledButton": "배경색이 완전히 채워진 강조 버튼",
    "FilledButtonTheme": "채워진 버튼 테마 설정",
    "FilledTonalButton": "톤이 약간 다운된 채워진 버튼 (보조 액션용)",
    "FilterQuality": "이미지 리사이징 등 필터링 품질 수준",
    "Flashlight": "기기 플래시라이트(손전등) 제어",
    "FletApp": "Flet 앱 메인 객체",
    "FletException": "Flet 기본 예외 처리 클래스",
    "FletUnimplementedPlatformEception": "해당 플랫폼에서 미지원 기능 호출 예외",
    "FletUnsupportedPlatformException": "지원하지 않는 플랫폼 예외",
    "FloatingActionButton": "플로팅 액션 버튼 (FAB, 둥근 메인 액션 버튼)",
    "FloatingActionButtonLocation": "플로팅 버튼 화면 위치",
    "FloatingActionButtonTheme": "플로팅 버튼 테마 설정",
    "FontWeight": "글꼴 굵기 설정",
    "Geolocator": "GPS 및 위치 정보 감지기",
    "GeolocatorActivityType": "위치 추적 활동 타입 (도보, 차량 등)",
    "GeolocatorAndroidSettings": "안드로이드 전용 위치 설정",
    "GeolocatorAppleSettings": "iOS/Mac 전용 위치 설정",
    "GeolocatorPermissionStatus": "위치 정보 권한 상태",
    "GeolocatorPosition": "현재 좌표 위치 데이터",
    "GeolocatorPositionAccuracy": "위치 추적 정확도 설정",
    "GeolocatorPositionChangeEvent": "위치 변경 감지 이벤트",
    "GeolocatorSettings": "위치 감지기 범용 설정",
    "GeolocatorWebSettings": "웹 환경 위치 감지 설정",
    "GestureDetector": "제스처 감지기 (터치, 스와이프, 핀치 줌 등 다양한 입력 감지)",
    "GradientTileMode": "그라데이션 반복 타일 모드",
    "GridView": "그리드 뷰 (바둑판 형태 스크롤 레이아웃)",
    "HapticFeedback": "햅틱 피드백 (진동) 제어",
    "HoverEvent": "마우스 호버(올려두기) 이벤트",
    "Icon": "내장 머티리얼 아이콘 위젯",
    "IconButton": "아이콘 버튼",
    "IconButtonTheme": "아이콘 버튼 테마 설정",
    "IconEnums": "아이콘 관련 열거형 속성",
    "IconTheme": "아이콘 범용 테마 설정",
    "IconValue": "아이콘 속성 값",
    "IconValueOrControl": "아이콘 값 또는 아이콘 위젯 컨트롤",
    "Icons": "Flet 내장 아이콘 이름 목록",
    "Image": "이미지 위젯",
    "ImageFit": "이미지 비율/맞춤 모드 (cover, contain 등)",
    "ImageRepeat": "이미지 반복 설정",
    "InputBorder": "텍스트 입력 필드 테마 (밑줄, 박스 등)",
    "InputFilter": "입력 필터 (특정 문자만 입력되게 제한)",
    "InteractiveViewer": "상호작용 뷰어 (이미지나 위젯을 확대/축소/이동 가능하게 만듦)",
    "InteractiveViewerInteractionEndEvent": "뷰어 상호작용 종료 이벤트",
    "InteractiveViewerInteractionStartEvent": "뷰어 상호작용 시작 이벤트",
    "InteractiveViewerInteractionUpdateEvent": "뷰어 상호작용 진행중 이벤트",
    "KeyboardEvent": "키보드 입력 이벤트",
    "KeyboardType": "키보드 종류 (숫자, 이메일, 전화번호 등)",
    "LabelPosition": "라벨 위치 (왼쪽, 오른쪽 등)",
    "LineChart": "선형(꺾은선) 그래프",
    "LineChartData": "선 그래프 전체 데이터셋",
    "LineChartDataPoint": "선 그래프의 개별 점(포인트) 좌표",
    "LineChartEvent": "선 그래프 상호작용 이벤트",
    "LineChartEventSpot": "선 그래프에서 이벤트가 발생한 지점",
    "LinearGradient": "선형 그라데이션",
    "ListTile": "리스트 타일 (아이콘, 제목, 부제목이 있는 전형적인 리스트 항목)",
    "ListTileStyle": "리스트 타일 스타일",
    "ListTileTheme": "리스트 타일 테마 설정",
    "ListTileTitleAlignment": "리스트 타일 텍스트 정렬",
    "ListView": "리스트 뷰 (세로 스크롤 목록)",
    "Locale": "로케일 (국가 및 언어 설정)",
    "LocaleConfiguration": "앱 로케일 설정",
    "LoginEvent": "로그인 인증 관련 이벤트",
    "LongPressEndEvent": "길게 누르기 종료 이벤트",
    "LongPressStartEvent": "길게 누르기 시작 이벤트",
    "Lottie": "로티 애니메이션 플레이어 위젯",
    "MainAxisAlignment": "주축(정방향) 정렬 방식",
    "Margin": "마진 (위젯 바깥쪽 여백)",
    "MarginValue": "마진 수치",
    "Markdown": "마크다운 렌더링 위젯 (텍스트를 마크다운 문법으로 변환)",
    "MarkdownCodeTheme": "마크다운 내 코드블록 테마",
    "MarkdownCustomCodeTheme": "마크다운 사용자 지정 코드 테마",
    "MarkdownExtensionSet": "마크다운 확장 문법 설정",
    "MarkdownStyleSheet": "마크다운 전용 스타일시트",
    "MenuBar": "데스크톱 스타일 메뉴 바 (상단 메뉴)",
    "MenuItemButton": "메뉴 바 내의 개별 메뉴 버튼",
    "MenuStyle": "메뉴 바 스타일",
    "MouseCursor": "마우스 커서 모양 설정",
    "MultiTapEvent": "멀티 터치/탭 이벤트",
    "NavigationBar": "네비게이션 바 (하단 탭 메뉴)",
    "NavigationBarDestination": "네비게이션 바의 탭 항목",
    "NavigationBarLabelBehavior": "네비게이션 바 라벨 표시 방식",
    "NavigationBarTheme": "네비게이션 바 테마",
    "NavigationDrawer": "네비게이션 서랍 (좌측에서 튀어나오는 사이드 메뉴)",
    "NavigationDrawerDestination": "서랍 메뉴의 개별 항목",
    "NavigationDrawerPosition": "서랍 메뉴가 나오는 위치 (좌/우)",
    "NavigationDrawerTheme": "서랍 메뉴 테마",
    "NavigationRail": "네비게이션 레일 (태블릿/PC 화면 좌측에 얇게 붙는 사이드바)",
    "NavigationRailDestination": "레일 바의 개별 항목",
    "NavigationRailLabelType": "레일 바 라벨 표시 방식",
    "NavigationRailTheme": "레일 바 테마",
    "NotchShape": "플로팅 버튼 주변 하단 앱바의 파인 모양(노치) 설정",
    "Number": "숫자 형식",
    "NumbersOnlyInputFilter": "숫자만 입력 가능하도록 제한하는 필터",
    "Offset": "오프셋 (위치 이동 좌표 값)",
    "OffsetValue": "오프셋 수치",
    "OnFocusEvent": "포커스(선택됨) 이벤트",
    "OnReorderEvent": "목록 순서 재배치 이벤트",
    "OnScrollEvent": "스크롤 동작 이벤트",
    "OptionalControlEventCallable": "선택적 컨트롤 이벤트 호출자",
    "OptionalEventCallable": "선택적 일반 이벤트 호출자",
    "OptionalNumber": "선택적 숫자 값",
    "OptionalString": "선택적 문자열 값",
    "Orientation": "화면 방향 (가로모드/세로모드)",
    "OutlinedBorder": "테두리선 박스 형태",
    "OutlinedButton": "아웃라인 버튼 (테두리만 있는 버튼)",
    "OutlinedButtonTheme": "아웃라인 버튼 테마",
    "Padding": "패딩 (위젯 안쪽 여백)",
    "PaddingValue": "패딩 수치",
    "Page": "페이지 (앱 창 자체를 다루는 최상위 객체)",
    "PageDisconnectedException": "페이지(소켓) 연결 끊김 예외",
    "PageMediaData": "페이지 화면 크기/미디어 정보",
    "PagePlatform": "현재 실행중인 플랫폼 (iOS, Android, Windows 등)",
    "PageTransitionTheme": "페이지 간 화면 전환 효과 테마",
    "PageTransitionsTheme": "전체 앱 페이지 전환 테마",
    "Pagelet": "페이지릿 (일부 영역만 독립적으로 스크롤/제어되는 위젯)",
    "Paint": "그리기(Paint) 브러시 설정 (Canvas 등에 사용)",
    "PaintLinearGradient": "그리기용 선형 그라데이션",
    "PaintRadialGradient": "그리기용 원형 그라데이션",
    "PaintSweepGradient": "그리기용 스윕(레이더형) 그라데이션",
    "PaintingStyle": "그리기 스타일 (채우기, 선 긋기)",
    "PermissionHandler": "기기 권한(카메라, 마이크 등) 요청/확인 핸들러",
    "PermissionStatus": "현재 권한 부여 상태",
    "PermissionType": "요청할 권한의 종류 (위치, 카메라 등)",
    "PieChart": "원형(파이) 차트",
    "PieChartEvent": "파이 차트 상호작용 이벤트",
    "PieChartSection": "파이 차트의 개별 조각 데이터",
    "Placeholder": "임시 공간(플레이스홀더)을 차지하는 위젯 (X자 표시 박스)",
    "PlaylistMode": "재생 목록 모드 (반복, 랜덤 등)",
    "PointerDeviceType": "입력 장치 종류 (마우스, 터치, 펜)",
    "PopupMenuButton": "팝업 메뉴 버튼",
    "PopupMenuItem": "팝업 메뉴의 개별 선택지",
    "PopupMenuPosition": "팝업 메뉴가 뜨는 위치",
    "PopupMenuTheme": "팝업 메뉴 테마",
    "ProgressBar": "가로형 진행 상태 바",
    "ProgressIndicatorTheme": "진행 상태 표시기 테마",
    "ProgressRing": "원형 회전 진행 상태 표시기 (로딩 뱅글뱅글)",
    "PubSubClient": "퍼블리시-서브스크라이브 클라이언트 (채팅 등 실시간 통신용)",
    "PubSubHub": "퍼블리시-서브스크라이브 중앙 허브",
    "QueryString": "웹 URL의 쿼리 스트링 관리",
    "RadialGradient": "원형 방사형 그라데이션",
    "Radio": "라디오 버튼 (단일 선택)",
    "RadioGroup": "라디오 버튼들을 묶어주는 그룹",
    "RadioTheme": "라디오 테마 설정",
    "RangeSlider": "범위 슬라이더 (시작점과 끝점을 모두 조절하는 막대)",
    "Ref": "위젯 참조 변수 (위젯 객체를 쉽게 찾고 제어하기 위한 포인터)",
    "ReorderableDraggable": "순서 변경 리스트 내의 드래그 가능 아이템",
    "ReorderableListView": "순서를 드래그해서 바꿀 수 있는 리스트 뷰",
    "ResponsiveNumber": "반응형 수치 (화면 크기에 따라 변하는 값)",
    "ResponsiveRow": "반응형 가로 레이아웃 (화면 폭이 좁아지면 자동으로 줄바꿈 처리)",
    "Rive": "Rive 애니메이션 플레이어 위젯",
    "Rotate": "위젯 회전 설정",
    "RotateValue": "회전 각도 값",
    "RoundedRectangleBorder": "둥근 모서리 사각형 테두리",
    "RouteChangeEvent": "라우트(페이지 URL 경로) 변경 이벤트",
    "Row": "가로 정렬 레이아웃",
    "SafeArea": "안전 영역 래퍼 위젯",
    "Scale": "위젯 크기 확대/축소 비율",
    "ScaleEndEvent": "크기 조절 제스처 종료 이벤트",
    "ScaleStartEvent": "크기 조절 제스처 시작 이벤트",
    "ScaleUpdateEvent": "크기 조절 제스처 진행중 이벤트",
    "ScaleValue": "크기 확대/축소 수치",
    "ScrollEvent": "스크롤 시 발생하는 이벤트",
    "ScrollMode": "스크롤 바 표시 모드 (자동, 항상 표시, 숨김 등)",
    "ScrollbarTheme": "스크롤 바 디자인 테마",
    "SearchBar": "검색 바 위젯",
    "SearchBarTheme": "검색 바 테마",
    "SearchViewTheme": "전체 화면 검색 뷰 테마",
    "Segment": "분할 버튼의 개별 세그먼트",
    "SegmentedButton": "머티리얼 스타일 분할 선택 버튼",
    "SegmentedButtonTheme": "분할 버튼 테마",
    "SelectionArea": "텍스트를 마우스로 드래그하여 복사할 수 있게 해주는 래퍼 위젯",
    "Semantics": "시각 장애인을 위한 스크린 리더용 의미론적 정보 태그 위젯",
    "SemanticsService": "앱 전체의 스크린 리더 기능 제어 서비스",
    "ShaderMask": "이미지나 위젯 위에 그라데이션 등 셰이더 마스크를 씌우는 위젯",
    "ShadowBlurStyle": "그림자 블러 스타일",
    "ShakeDetector": "스마트폰 흔들기 감지기",
    "Size": "크기 (너비/높이) 객체",
    "Slider": "슬라이더 막대",
    "SliderInteraction": "슬라이더 상호작용 제어",
    "SliderTheme": "슬라이더 테마",
    "SnackBar": "스낵바 (하단에 짧게 뜨는 알림창)",
    "SnackBarBehavior": "스낵바 동작 방식 (플로팅, 고정)",
    "SnackBarTheme": "스낵바 테마",
    "Stack": "스택 (위젯들을 포토샵 레이어처럼 겹치게 배치하는 컨테이너)",
    "StackFit": "스택 내부 자식들의 크기 맞춤 방식",
    "StadiumBorder": "경기장 모양(양끝이 완벽한 반원)의 테두리",
    "StrokeCap": "선(Stroke) 끝부분 처리 모양 (둥글게, 평평하게 등)",
    "StrokeJoin": "선 꺾임(모서리) 부분 처리 모양",
    "SubmenuButton": "메뉴 안의 서브 메뉴 버튼",
    "SupportsStr": "문자열 변환 지원 믹스인",
    "SweepGradient": "레이더 스캔 형태의 둥근 그라데이션",
    "Switch": "스위치 토글 버튼",
    "SwitchTheme": "스위치 테마",
    "SystemOverlayStyle": "시스템 오버레이 스타일 (스마트폰 상단 시간/배터리 표시줄 색상 제어)",
    "Tab": "탭 바 안의 개별 탭 버튼",
    "TabAlignment": "탭 버튼 정렬 방식",
    "Tabs": "탭 레이아웃 뷰어 (탭을 누르면 화면 전환)",
    "TabsTheme": "탭 테마",
    "TapEvent": "클릭/터치(탭) 이벤트",
    "TemplateRoute": "URL 라우트 템플릿 처리기",
    "Text": "텍스트 위젯",
    "TextAffinity": "텍스트 커서 친화도 방향",
    "TextAlign": "텍스트 정렬 (왼쪽, 가운데, 오른쪽)",
    "TextBaseline": "텍스트 베이스라인(밑줄 기준선) 정렬",
    "TextButton": "텍스트 버튼 (배경이 없는 글씨 버튼)",
    "TextButtonTheme": "텍스트 버튼 테마",
    "TextCapitalization": "텍스트 대소문자 자동 변환 설정",
    "TextDecoration": "글자 꾸미기 (밑줄, 취소선 등)",
    "TextDecorationStyle": "글자 꾸미기 선 스타일 (실선, 점선 등)",
    "TextField": "텍스트 입력 필드",
    "TextOnlyInputFilter": "문자만 입력 가능하도록 제한하는 필터",
    "TextOverflow": "텍스트가 영역을 넘어갈 때 처리 방식 (말줄임표 등)",
    "TextSelection": "텍스트 선택 영역 객체",
    "TextSpan": "텍스트의 특정 구간만 색상/폰트를 다르게 지정할 때 쓰는 부분 텍스트",
    "TextStyle": "텍스트 폰트/색상 스타일 설정",
    "TextTheme": "텍스트 전역 테마 설정",
    "TextThemeStyle": "머티리얼 디자인 표준 텍스트 테마 속성 (Headline1, BodyText 등)",
    "Theme": "앱 전체의 디자인/색상 통합 테마 설정 클래스",
    "ThemeMode": "테마 모드 (라이트, 다크, 시스템 자동)",
    "TileAffinity": "리스트 타일의 아이콘/텍스트 배치 방향",
    "TimePicker": "시간 선택기 (아날로그 시계 모양 팝업)",
    "TimePickerEntryMode": "시간 선택기 입력 모드 (시계 다이얼 vs 직접 타이핑)",
    "TimePickerEntryModeChangeEvent": "시간 입력 모드 변경 이벤트",
    "TimePickerTheme": "시간 선택기 테마",
    "Tooltip": "툴팁 (마우스를 올렸을 때 나타나는 풍선 도움말)",
    "TooltipTheme": "툴팁 테마",
    "TooltipTriggerMode": "툴팁 작동 방식 (호버, 길게 누르기 등)",
    "TransparentPointer": "투명 포인터 (마우스 이벤트를 아래에 있는 위젯으로 통과시킴)",
    "UrlTarget": "URL 링크 클릭 시 열림 방식 (새 탭, 현재 탭 등)",
    "VerticalAlignment": "세로축(Y축) 정렬 방식",
    "VerticalDivider": "세로 방향 구분선",
    "Video": "비디오 플레이어 위젯",
    "VideoConfiguration": "비디오 기본 설정",
    "VideoMedia": "비디오 미디어 파일 정보",
    "VideoSubtitleConfiguration": "비디오 자막 설정",
    "View": "라우터에서 사용하는 개별 화면(페이지) 객체",
    "ViewPopEvent": "뒤로 가기(View Pop) 발생 이벤트",
    "VisibilityMode": "가시성 모드 (숨김, 보임 처리 방식)",
    "VisualDensity": "시각적 밀도 (위젯 간의 기본 간격 조밀도)",
    "WEB_BROWSER": "웹 브라우저 상수",
    "WebRenderer": "웹 렌더링 엔진 (CanvasKit, HTML 등)",
    "WebView": "웹페이지를 앱 안에 띄우는 웹뷰 위젯",
    "WebviewConsoleMessageEvent": "웹뷰 내부 브라우저 콘솔 메시지 수신 이벤트",
    "WebviewJavaScriptEvent": "웹뷰 자바스크립트 통신 이벤트",
    "WebviewLogLevelSeverity": "웹뷰 로그 심각도 레벨",
    "WebviewRequestMethod": "웹뷰 URL 요청 메소드 (GET, POST)",
    "WebviewScrollEvent": "웹뷰 스크롤 동작 이벤트",
    "Window": "PC용 데스크톱 윈도우 창 제어 모듈",
    "WindowDragArea": "PC 창의 제목 표시줄처럼 창 전체를 드래그해서 옮길 수 있는 영역 위젯",
    "WindowEvent": "PC 윈도우 창 이벤트 (최소화, 종료 등)",
    "WindowEventType": "윈도우 이벤트 타입 열거형",
    "WindowResizeEvent": "창 크기 조절 이벤트",

    # --- 파이썬 내장 속성 및 패키지 내부 모듈 ---
    "__builtins__": "파이썬 내장 함수 모음 (무시 가능)",
    "__cached__": "파이썬 캐시 경로 (무시 가능)",
    "__doc__": "모듈/클래스 설명문서 속성 (무시 가능)",
    "__file__": "현재 모듈의 실제 파일 경로 (무시 가능)",
    "__loader__": "파이썬 모듈 로더 (무시 가능)",
    "__name__": "현재 모듈 이름 (무시 가능)",
    "__package__": "현재 패키지 이름 (무시 가능)",
    "__path__": "패키지 경로 (무시 가능)",
    "__spec__": "모듈 스펙 정보 (무시 가능)",

    # --- Flet 하위 패키지 모듈 ---
    "alignment": "정렬 관련 하위 모듈 (top_left, center 등)",
    "app": "Flet 앱 실행 함수 (데스크톱/모바일 구동용)",
    "app_async": "비동기(Async) 방식의 Flet 앱 실행 함수",
    "auth": "OAuth, Github 등 사용자 인증/로그인 관련 하위 모듈",
    "border": "테두리 스타일 관련 하위 모듈",
    "border_radius": "테두리 둥글기 세부 설정 하위 모듈",
    "context": "앱 실행 컨텍스트(환경) 관리 모듈",
    "core": "Flet 코어(핵심) 시스템 하위 모듈",
    "dropdown": "드롭다운 세부 모듈",
    "dropdownm2": "드롭다운(Material 2) 세부 모듈",
    "margin": "마진 여백 계산 하위 모듈",
    "padding": "패딩 여백 계산 하위 모듈",
    "painting": "그리기, 색칠 관련 헬퍼 하위 모듈",
    "size": "위젯 크기 계산 하위 모듈",
    "utils": "유틸리티 도구(기타 헬퍼 함수) 하위 모듈",
    "version": "설치된 Flet 라이브러리의 현재 버전 정보"
}
import inspect
from enum import Enum
# 텍스트 파일 생성 실행
with open("t_flet_widget_korean_deep.txt", "w", encoding='utf-8') as f:
    # 1. 상단 목차 생성
    count = 1
    print(f"{'=' * 50}\n  목차\n{'=' * 50}", file=f)
    for key, value in flet_korean_dict.items():
        print(f"[{count}] {key} : {value}", file=f)
        count = count + 1

    # 2. 상세 설명서 및 무삭제 값 추출 + [하위 모듈 탐색 & 중복 필터링]
    count = 1
    for key, value in flet_korean_dict.items():
        print(f"\n\n{'=' * 50}\n  [{count}] {key} : {value}\n{'=' * 50}", file=f)

        try:
            obj = getattr(flet, key)
        except AttributeError:
            continue

        # A. 구조(Signature) 추출
        sig_str = ""
        try:
            if inspect.isclass(obj) or inspect.isfunction(obj):
                sig = inspect.signature(obj)
                sig_str = f"{key}{sig}"
                print(f"구조(Signature):\n  {sig_str}\n", file=f)
        except ValueError:
            pass

            # B. 영문 설명서(Docstring) 추출 및 [중복 제거 로직]
        doc = inspect.getdoc(obj)
        if doc:
            is_duplicate = False
            if sig_str:
                # 공백과 줄바꿈, 그리고 반환타입(-> None 등)을 제거하고 순수 내용만 비교
                clean_doc = doc.replace(" ", "").replace("\n", "")
                clean_sig = sig_str.replace(" ", "").replace("\n", "").split("->")[0]
                clean_sig_full = sig_str.replace(" ", "").replace("\n", "")

                # 설명서가 구조와 완벽히 똑같으면 중복으로 판정
                if clean_doc == clean_sig or clean_doc == clean_sig_full:
                    is_duplicate = True

            # 중복이 아닐 때만 영문 설명서 출력
            if not is_duplicate:
                print(f"영문 설명서(Docstring):\n{doc}\n", file=f)

        # C. Enum 값(Icons, Colors 등) 무삭제 출력
        if inspect.isclass(obj) and issubclass(obj, Enum):
            print("내부 값(Enum Values) - 무삭제:", file=f)
            for enum_item in obj:
                print(f"  - {enum_item.name} = '{enum_item.value}'", file=f)

        # D. 모듈(폴더) 하위 세부 함수 탐색
        if inspect.ismodule(obj):
            print(f"[{key}] 하위 세부 함수 탐색:", file=f)
            sub_items_found = False

            for sub_name in dir(obj):
                if sub_name.startswith("_"):
                    continue

                sub_obj = getattr(obj, sub_name, None)
                if inspect.ismodule(sub_obj):
                    continue

                try:
                    if inspect.isfunction(sub_obj) or inspect.isclass(sub_obj):
                        sub_sig = inspect.signature(sub_obj)
                        sub_sig_str = f"{key}.{sub_name}{sub_sig}"
                        print(f"\n  {sub_sig_str}", file=f)

                        sub_doc = inspect.getdoc(sub_obj)
                        if sub_doc:
                            # 하위 함수도 똑같이 중복 체크 적용
                            sub_clean_doc = sub_doc.replace(" ", "").replace("\n", "")
                            sub_clean_sig = sub_sig_str.replace(" ", "").replace("\n", "").split("->")[0]
                            sub_clean_sig_full = sub_sig_str.replace(" ", "").replace("\n", "")

                            if sub_clean_doc != sub_clean_sig and sub_clean_doc != sub_clean_sig_full:
                                indented_doc = "\n".join([f"     {line}" for line in sub_doc.split("\n")])
                                print(f"{indented_doc}", file=f)

                        sub_items_found = True
                except ValueError:
                    pass

            if not sub_items_found:
                print("  (내부에 탐색할 하위 구조가 없습니다.)", file=f)
                pass

        count = count + 1